# Generated by Django 3.0.4 on 2020-03-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMap',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.AdminMap')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('banned', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.AdminMap')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_id', models.IntegerField(blank=True)),
                ('downvote_id', models.IntegerField(blank=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.Message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.Users')),
            ],
        ),
        migrations.AddField(
            model_name='adminmap',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndoriumAPI.Users'),
        ),
    ]
